name = "scp-latom-node-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[vars]
JWT_SECRET = "scp-latom-node-change-me-in-production"
CORS_ORIGIN = "https://scp-docs.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "scp-latom-node"
database_id = "85985e6c-c19e-43e3-9fc5-45754f2a215c"
